spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UrbanNestDB
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  pathsToMatch: /api/**

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
